### ISSUE TITLE
Please bump axios to newer version to resolve "cached DNS errors" issues

### ISSUE THREAD

**Issue by mman** [dubocr/overkiz-client#11]
I am using Homebridge Tahoma and thus the Overkiz Client for many years, and I have noticed one persistent bug. When the internet goes down, HomeBridge Tahome via (now outdated) `axios` fails to resolve the tahomalink hostname with `getaddrinfo failed: EAGAIN` and never recovers.

It seems to be a long standing known issue in nodejs that it improperly caches dns failures and many apps seem to workaround this by using `dns.lookup` to make sure DNS resolution is retried properly when internet comes back.

This package uses super outdated version of `axios` and bumping it to the latest version should help.

https://github.com/axios/axios/releases/tag/v1.7.2

**Comment by dubocr** [comment]
Hi,

Done in [a23f09f](https://github.com/dubocr/overkiz-client/commit/a23f09f0296543f5f84bb11f2968a2c1050a376b)

**Comment by mman** [comment]
Thanks @dubocr, will put it into production and see if it helps resolve the problems.
