### ISSUE TITLE
Ajout du support de Hi-Kumo

### ISSUE THREAD

**Issue by chabou-san** [dubocr/overkiz-client#5]
Bonjour,

En furetant sur internet, j'ai trouvé ce repo : https://github.com/iMicknl/python-tahoma-api/blob/master/pyhoma/const.py qui semble indiquer que le support de `Hi-Kumo` en tant que système de chauffage comme `Somfy` est basé sur `Overkiz` également.
Est-ce qu'il est possible de rajouter ce support afin que `Hi-Kumo` (version "Europe" en ce qui me concerne) soit disponible dans `homebridge-tahoma` ?

**Comment by phimage** [comment]
Rajouter soit même et faire une PR peut aider le dev qui n'a pas forcément du temps à consacrer

Si il y a rien de particulier tu peux t'inspirer de https://github.com/dubocr/overkiz-client/pull/6/files et donc tester avec ton matériel

**Comment by dubocr** [comment]
Bonjour,

De nouveaux services (donc Hi Kumo) viennent d'être ajoutés. Désolé pour le délai.

**Comment by chabou-san** [comment]
Merci beaucoup ! Pas de problème pour le délai, vous faites ça gratuitement sur votre temps libre, donc je n’avais pas d’exigences sur le sujet. Merci encore de l’avoir fait. 👍
